In [2]:
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.tools as tls
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import shuffle
import seaborn as sns
import time
from IPython.display import clear_output
%matplotlib inline
class ReadData(object):
    def __init__(self,datasetName='Iris.csv'):
        self.datasetName=datasetName
    def readData(self):
        df = pd.read_csv('Iris.csv')   
        df = df.drop(['Id'],axis=1)
        #rows = list(range(100,150))
        #df = df.drop(df.index[rows]) 
        Y = []
        target = df['Species']
        for val in target:
            if(val == 'Iris-setosa'):
                Y.append(0)
            elif(val=='Iris-versicolor'):
                Y.append(1)
            else:
                Y.append(2)
        df = df.drop(['Species'],axis=1)
        X = df.values.tolist()
        datafeatureSize=50
        labels = np.array([0]*datafeatureSize + [1]*datafeatureSize + [2]*datafeatureSize)
        Y = np.zeros((datafeatureSize*3, 3))
        for i in range(datafeatureSize*3):  
            Y[i, labels[i]] = 1
        X, Y = shuffle(X,Y)
        X=np.array(X)
        Y=np.array(Y)
        forTestY=Y[120:]
        forTestX=X[120:,:]
        X=X[0:120,:]
        Y=Y[0:120,:]
        return X,Y,forTestX,forTestY
r=ReadData()
[X,Y,forTestX,forTestY]=r.readData()

array([[6. , 3.4, 4.5, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [4.6, 3.2, 1.4, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [6.3, 3.4, 5.6, 2.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.7, 3.8, 1.7, 0.3],
       [4.8, 3.4, 1.6, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [6.5, 3. , 5.8, 2.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [6.9, 3.2, 5.7, 2.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.1, 3.5, 1.4, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6. , 2.7, 5.1, 1.6],
       [7.2, 3.6, 6.1, 2.5],
       [5. , 3.4, 1.6, 0.4],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.7, 4.1, 1. ],
       [5.4, 3. , 4.5, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3

In [64]:
import numpy as np
class KMeans(object):
    def __init__(self,numClusters,numIterations=1000,isTrain=True,randomState=123):
        self.numClusters=numClusters
        self.numIterations=numIterations
        self.isTrain=isTrain
        self.randomState=randomState
    def initializeCentroids(self,X):#create random centroids
        np.random.RandomState(self.randomState)
        random_idx = np.random.permutation(X.shape[0])
        centroids = X[random_idx[:self.numClusters]]
        return centroids
    #def updateCentrois(X,labels):
    def getDistanceBetweenPointsAndCentroids(self,X,centroids):#using ecuclidean distance ||x-c||^2
        distance = np.zeros((X.shape[0], self.numClusters))
        for k in range(self.numClusters):
            distance[:, k] =np.square(norm(X - centroids[k, :], axis=1))
        return distance
    def getClosestCluster(self, distance):#function for set labels to cluster 
        return np.argmin(distance, axis=1)
    def updateCentroids(self, X, labels):#update new centroids
        centroids = np.zeros((self.numClusters, X.shape[1]))
        for k in range(self.numClusters):
            centroids[k, :] = np.mean(X[labels == k, :], axis=0)
        return centroids
    def fit(self, X):
        self.centroids = self.initializeCentroids(X)
        for i in range(self.numIterations):
            oldCentroids = self.centroids
            distance = self.getDistanceBetweenPointsAndCentroids(X, oldCentroids)
            self.labels = self.getClosestCluster(distance)
            self.centroids = self.updateCentroids(X, self.labels)
            if np.all(oldCentroids == self.centroids):
                break
        return  self.centroids
if __name__=='__main__':
    km=KMeans(3)
    centroides=km.fit(X)
    print(centroides)

[[5.82888889 2.70444444 4.35333333 1.40222222]
 [5.00487805 3.41463415 1.47560976 0.24146341]
 [6.87058824 3.07941176 5.73235294 2.06470588]]
